### ISSUE TITLE
Loading different ur robot model

### ISSUE THREAD

**Issue by KevinGalassi** [bi3ri/dual_arm_demo#1]
Hi
I'm trying to use your package and it's work perfectly, but i have some issue in loading different robots urdf model, in particular i would like to have an ur5 for one arm and an ur5e for the other one.  
I changed groot xacro :
<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find ur_description)/urdf/inc/ur5_macro.xacro" />

  <xacro:macro name="groot" params="parent *origin">

    <joint name="groot_world_joint" type="fixed">
      <parent link="${parent}" />
      <child link="groot_base_link" />
      <xacro:insert_block name="origin" />
    </joint>

    <xacro:include filename="$(find ur_gazebo)/urdf/ur_macro.xacro" />

    
    <xacro:arg name="joint_limit_params" default="$(find ur_description)/config/ur5/joint_limits.yaml" />
    <xacro:arg name="physical_params" default="$(find ur_description)/config/ur5/physical_parameters.yaml" />
    <xacro:arg name="kinematics_params" default="$(find ur_description)/config/ur5/default_kinematics.yaml" />
    <xacro:arg name="visual_params" default="$(find ur_description)/config/ur5/visual_parameters.yaml" />
    
    <xacro:arg name="transmission_hw_interface" default="hardware_interface/PositionJointInterface" />
    <xacro:arg name="safety_limits" default="false" />
    <xacro:arg name="safety_pos_margin" default="0.15" />
    <xacro:arg name="safety_k_position" default="20" />

    
    <xacro:ur_robot_gazebo
      prefix="groot_"
      joint_limits_parameters_file="$(arg joint_limit_params)"
      kinematics_parameters_file="$(arg kinematics_params)"
      physical_parameters_file="$(arg physical_params)"
      visual_parameters_file="$(arg visual_params)"
      transmission_hw_interface="$(arg transmission_hw_interface)"
      safety_limits="$(arg safety_limits)"
      safety_pos_margin="$(arg safety_pos_margin)"
      safety_k_position="$(arg safety_k_position)"
      load_gazebo_ros_control_plugin="false"
    />

  </xacro:macro>
</robot>

but i'm not seeing the model i want. ( The base of the two robots are the same while the newer model is slighty different from the old)
Do you have any suggestion?

**Comment by bi3ri** [comment]
Bonjorno Kevin!

I am not sure if I understood your problem correctly. For me if I change Groot to a ur5 robot I have no Issues:
![image](https://user-images.githubusercontent.com/82565675/160139643-397e1f6b-57df-4006-ac80-b0752202883d.png)

You did not copy the hole xacro file. Did you change the import in line 4? Are you using my forked universal_robot pkg?

Here you can find the my adapted groot file:

```xml
<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find ur_description)/urdf/inc/ur5_macro.xacro" />

  <xacro:macro name="groot" params="parent *origin">

    <joint name="groot_world_joint" type="fixed">
      <parent link="${parent}" />
      <child link="groot_base_link" />
      <xacro:insert_block name="origin" />
    </joint>

    <xacro:include filename="$(find ur_gazebo)/urdf/ur_macro.xacro" />

    <!--Declare arguments -->
    <xacro:arg name="joint_limit_params" default="$(find ur_description)/config/ur5/joint_limits.yaml" />
    <xacro:arg name="physical_params" default="$(find ur_description)/config/ur5/physical_parameters.yaml" />
    <xacro:arg name="kinematics_params" default="$(find ur_description)/config/ur5/default_kinematics.yaml" />
    <xacro:arg name="visual_params" default="$(find ur_description)/config/ur5/visual_parameters.yaml" />
    <!--
          legal values:
            - hardware_interface/PositionJointInterface
            - hardware_interface/VelocityJointInterface
            - hardware_interface/EffortJointInterface
      
          NOTE: this value must correspond to the controller configured in the
                controller .yaml files in the 'config' directory.
        -->
    <xacro:arg name="transmission_hw_interface" default="hardware_interface/PositionJointInterface" />
    <xacro:arg name="safety_limits" default="false" />
    <xacro:arg name="safety_pos_margin" default="0.15" />
    <xacro:arg name="safety_k_position" default="20" />

    <!-- Instantiate the Gazebo robot and pass it all the required arguments. -->
    <xacro:ur_robot_gazebo
      prefix="groot_"
      joint_limits_parameters_file="$(arg joint_limit_params)"
      kinematics_parameters_file="$(arg kinematics_params)"
      physical_parameters_file="$(arg physical_params)"
      visual_parameters_file="$(arg visual_params)"
      transmission_hw_interface="$(arg transmission_hw_interface)"
      safety_limits="$(arg safety_limits)"
      safety_pos_margin="$(arg safety_pos_margin)"
      safety_k_position="$(arg safety_k_position)"
      load_gazebo_ros_control_plugin="false"
    />

  </xacro:macro>
</robot>
```

**Comment by bi3ri** [comment]
@KevinGalassi Did you find a solution for your issue?

**Comment by KevinGalassi** [comment]
Yes, the problem was that both of xacros were using these parameters, but since they have the same name they were used by both of the robot, I chanfed the name ad assigned it to the two robot and at the end i had two differents model.

``
<xacro:arg name="joint_limit_params" default="$(find ur_description)/config/ur16e/joint_limits.yaml" />
<xacro:arg name="physical_params" default="$(find ur_description)/config/ur16e/physical_parameters.yaml" />
<xacro:arg name="kinematics_params" default="$(find ur_description)/config/ur16e/default_kinematics.yaml" />
<xacro:arg name="visual_params" default="$(find ur_description)/config/ur16e/visual_parameters.yaml" />
``

In your pic you were using two ur5e, the base in the old model is slighty different.

**Comment by bi3ri** [comment]
This could be, but as you can see I changed the xacro to ur5 so if there is a problem it is within the package of the universal robot.
