### ISSUE TITLE
How to generate to arms for one MoveIt Setup Assistant config

### ISSUE THREAD

**Issue by federatedreserve** [bi3ri/dual_arm_demo#2]
Sorry but I was just wondering how did you use the setup assistant to generate a single config for two arms? Did you manually just modify the setup assistant output for one of the arms and add the other arm in certain places?

**Comment by bi3ri** [comment]
@federatedreserve Hello, sorry for my late response. I used the setup assistant for both arms and afterwars adjusted the config manually.
